Iter9
mrkovshik/yametrics pull request #11
Opened 2024-04-01 09:45 UTC by mrkovshik

2024-04-04 14:18 UTC, rktkov requested changes

2024-04-04 14:18 UTC, rktkov commented on internal/utl/address.go
> +func ValidateAddress(addr string) bool {
Может использовать существующую функцию - https://pkg.go.dev/net/url#Parse

2024-04-04 14:18 UTC, rktkov commented on internal/utl/address.go
> +package utl
Почему бы не назвать util

2024-04-04 14:18 UTC, rktkov commented on internal/storage/storage.go
> +	IStorage interface {
Имя интерфейса должно быть отглагольным существительном. И не надо использовать Префикс I.
Так же у тебя всего лишь одно определение типа, не стоит группу делать.
Определение интерфейса надо перенести в пакет, где он будет использоваться.

2024-04-04 14:18 UTC, rktkov commented on internal/storage/map_storage.go
> +func NewMapStorage() *MapStorage {
Функция инициализатор должна возвращать интерфейс, а не структуру. Так код станет расширяемый

2024-04-04 14:18 UTC, rktkov commented on internal/service/server/service.go
> +	config "github.com/mrkovshik/yametrics/internal/config/server"
А вот тут импорты опять не сгруппированы.

2024-04-04 14:18 UTC, rktkov commented on internal/service/server/service.go
> +	Storage storage.IStorage
А точно поля будут использоваться где-то кроме пакета? Стоит поля сделать закрытыми.

2024-04-05 01:54 UTC, mrkovshik commented on internal/utl/address.go
> +func ValidateAddress(addr string) bool {
Переделал, но не на предложенную функцию, а на функции из пакета net. Они мне показались более подходящими для этого случая.

2024-04-05 01:54 UTC, mrkovshik commented on internal/utl/address.go
> +package utl
исправлено

2024-04-05 02:15 UTC, mrkovshik commented on internal/storage/storage.go
> +	IStorage interface {
> Определение интерфейса надо перенести в пакет, где он будет использоваться
Этот интерфейс у меня используется как в агенте, так и в сервере, поэтому я и сделал его отдельным файликом. Не понятно, куда его переносить

2024-04-05 02:17 UTC, mrkovshik commented on internal/storage/map_storage.go
> +func NewMapStorage() *MapStorage {
Исправлено

2024-04-05 02:18 UTC, mrkovshik commented on internal/storage/storage.go
> +	IStorage interface {
> Имя интерфейса должно быть отглагольным существительном. И не надо использовать Префикс I.

исправлено

2024-04-05 02:46 UTC, mrkovshik commented on internal/service/server/service.go
> +	Storage storage.IStorage
переделал здесь и в пакете service/agent

2024-04-05 02:47 UTC, mrkovshik commented on internal/service/server/service.go
> +	config "github.com/mrkovshik/yametrics/internal/config/server"
сгруппировал

2024-04-09 10:30 UTC, rktkov commented on internal/storage/storage.go
> +	IStorage interface {
> > Определение интерфейса надо перенести в пакет, где он будет использоваться
> 
> Этот интерфейс у меня используется как в агенте, так и в сервере, поэтому я и сделал его отдельным файликом. Не понятно, куда его переносить

Можешь в пакет internal. Или другой ближайший пакет, который объединяет пакеты агента и севера.

2024-04-09 10:30 UTC, rktkov approved these changes

2024-05-05 12:28 UTC, merged