Iter15
mrkovshik/yametrics pull request #17
Opened 2024-04-23 03:24 UTC by mrkovshik

2024-04-25 12:19 UTC, rktkov requested changes

2024-04-25 12:19 UTC, rktkov commented on internal/storage/map.go
> +	Mu      sync.RWMutex
Структура закрытая, т.е вне пакета не будет использована. Поэтому и поля можно сделать закрытыми.

2024-04-25 12:19 UTC, rktkov commented on internal/service/server/service.go
> +	"go.uber.org/zap"
import

Возьмите в привычку сортировать импортируемые пакеты следующим образом:
1. пакеты стандартной библиотеки
2. внешние установленные пакеты
3. внутренние пакеты проекта

Для того, чтобы разные автоматические инструменты их не пересортировывали, разделяйте блоки пустой строкой.

см. комментарий про порядок импорта
https://stackoverflow.com/questions/24790175/when-is-the-init-function-run

2024-04-25 12:19 UTC, rktkov commented on internal/service/agent/service.go
> +		time.Sleep(time.Duration(a.config.ReportInterval) * time.Second)
Стоит переписать с использование timer.Ticker

2024-04-25 12:19 UTC, rktkov commented on internal/service/agent/service.go
> +		time.Sleep(time.Duration(a.config.PollInterval) * time.Second)
см. комментарий выше

2024-04-26 03:00 UTC, mrkovshik commented on internal/storage/map.go
> +	Mu      sync.RWMutex
Исправлено

2024-04-26 03:00 UTC, mrkovshik commented on internal/service/server/service.go
> +	"go.uber.org/zap"
Исправлено

2024-04-26 03:00 UTC, mrkovshik commented on internal/service/agent/service.go
> +		time.Sleep(time.Duration(a.config.ReportInterval) * time.Second)
Исправлено

2024-04-26 03:01 UTC, mrkovshik commented on internal/service/agent/service.go
> +		time.Sleep(time.Duration(a.config.PollInterval) * time.Second)
Исправлено

2024-05-05 09:38 UTC, rktkov approved these changes

2024-05-05 12:28 UTC, merged