Iter18
mrkovshik/yametrics pull request #19
Opened 2024-06-24 12:55 UTC by mrkovshik

2024-06-26 15:42 UTC, far4599 commented
В целом нормально. Нужно переделать хендлеры из-за проблемы с контекстом. 

Общие рекомендации:
1. Упростить тесты. В них очень много текста, их трудно читать и понимать, что там происходит. Улучшить можно с помощью разбиения на маленькие независимые тесты функции, или тесты в табличном виде. 
2. В коде стоит использовать разделение кода на логические блоки с помощью пустых строк. Это сильно упрощает процесс чтения кода. Сейчас многие метоыд выглядят как непрерывная простыня и в этом очень сложно разобраться.

2024-06-26 15:42 UTC, far4599 requested changes

2024-06-26 15:42 UTC, far4599 commented on bm_test.go
лучше переименовать файл в benchmark_test, так как слово benchmark сразу понятно, а bm - нет

2024-06-26 15:42 UTC, far4599 commented on api/rest/api.go
> +	s.logger.Fatal(http.ListenAndServe(s.config.Address, r))
лучше отделить логику создания хендлеров от запуска сервера - тогда в тестах ты сможешь тестировать весь роутер без необходимости запускать сервер на реальном порту

2024-06-26 15:42 UTC, far4599 commented on api/rest/doc.go
👍
отличная получилась дока

2024-06-26 15:42 UTC, far4599 commented on api/rest/api.go
> +func NewServer(service api.Service, config *config.ServerConfig, logger *zap.SugaredLogger) *Server {
как рекомендация, предлагаю не использовать в функциональных пакетах ссылки на общий пакет config. это создает завязку множества пакетов на один и приводит к усложнению поддержки всех пакетов. например, при добавлении поля в конфиг придется менять сразу 2 пакета. рефакторинг в config может привести ко множеству бесполезных изменений в функциональных пакетах. и тп

хорошей практикой является хранение всех структур функциональных пакетов в нем самом. а в пакете config можно использовать встраивание или вообще избавиться от пакета config
```
package rest

type Config struct {...}
```

```
package config/main

type Config struct {
  RESTConfig rest.Config
}
```

2024-06-26 15:42 UTC, far4599 commented on api/rest/example_test.go
> +func Example() {
можно изменить сигнатуру на сигнатуру теста и тогда пользователь в IDE сможет запустить пример в один клик

2024-06-26 15:42 UTC, far4599 commented on api/rest/example_test.go
не очень понятно, почему этот пример лежит в пакете rest. может стоит его перенести в корень проекта?

2024-06-26 15:42 UTC, far4599 commented on api/rest/handlers.go
>  func (s *Server) UpdateMetricFromJSON(ctx context.Context) func(res http.ResponseWriter, req *http.Request) {
`(res http.ResponseWriter, req *http.Request)` имена аргументов похожи на что-то из мира nodejs =), в Go чаще всего используются такие варианты 
```
(w http.ResponseWriter, r *http.Request)
(rw http.ResponseWriter, r *http.Request)
```

2024-06-26 15:42 UTC, far4599 commented on api/rest/handlers.go
>  		if _, err := res.Write([]byte("Gauge successfully updated")); err != nil {
в блоке if нет смысла делать вызов `http.Error(res, "error res.Write", http.StatusInternalServerError)`, потому что если тебе не удалось записать байты в строке `err := res.Write([]byte("Gauge successfully updated"))`, то и ошибку не получится туда записать. 
можно оставить только логгирование ошибки

2024-06-26 15:42 UTC, far4599 commented on api/rest/handlers.go
>  func (s *Server) UpdateMetricFromJSON(ctx context.Context) func(res http.ResponseWriter, req *http.Request) {
кажется, что у тебя тут большая проблема с контекстом. стоит еще раз пройтись по теме контекста из первого спринта. 
проблема тут в том, что ты фиксируешь в замыкании какой-то контекст и используешь его в методах отдельных запросов. 
дело в том, что контекст - это механизм управления жизненным циклом определенной работы. в случае с http сервером - это цепочка запросов от одно сервера к твоему и дальше к другим серверам, базам данных, сервисам. 
если какое-то звено считает, что работу больше не нужно делать, то оно терминирует контекст и таким образом сообщает всем нижележащим участникам цепочки, что больше работу выполнять не нужно, можно ее завершить на том месте, где они находятся сейчас. 

посмотри на методы структуры http.Request, может быть найдешь там что-нибудь подходящее 😉

2024-06-26 15:42 UTC, far4599 commented on api/rest/handlers.go
>  func (s *Server) UpdateMetricsFromJSON(ctx context.Context) func(res http.ResponseWriter, req *http.Request) {
тут тоже же самое

2024-06-26 15:42 UTC, far4599 commented on api/rest/handlers.go
> +			http.Error(res, "error res.Write", http.StatusInternalServerError)
проверь, где встречается эта строка. я думаю, что в ней должна быть ошибка err, а не "error res.Write"

2024-06-26 15:42 UTC, far4599 commented on api/rest/handlers.go
>  		var ctx = context.Background()
так, а тут вообще контекст создается в функции. тоже заявочка на исправление

2024-06-26 15:42 UTC, far4599 commented on api/rest/middleware.go
>  		clientSig := r.Header.Get(`HashSHA256`)
коммент относится к строке `body, err := io.ReadAll(r.Body)` - после прочтения тела запроса, его нужно закрыть через `defer r.Body.Close()`. 

проверять r.Body на nil не нужно, но почему?

2024-06-26 15:42 UTC, far4599 commented on api/rest/rest_api_test.go
тут находится большой и сложный тест, его следует переделать в следующем спринте. убери связь между тест кейсами, не используй реальный сервер, а только роутер в тестах

2024-06-26 15:42 UTC, far4599 commented on cmd/agent/agent.go
обычно файл, в котором находится метод main, называют main.go

2024-06-26 15:42 UTC, far4599 commented on cmd/server/server.go
> +	if err := metricService.StoreMetrics(ctx); err != nil {
правильно я понимаю, что этот метод должен быть вызван, когда сервер завершит свою работу?

2024-06-26 15:42 UTC, far4599 commented on internal/service/agent/request.go
>  	req, err := http.NewRequest(http.MethodGet, "", nil)
в пакете httptest есть структура тестового request, может быть стоит использовать его?

2024-06-26 15:42 UTC, far4599 commented on internal/service/storage.go
>  type Storage interface {
лучше избавиться от супер-интерфейсов. кажется, что они делают жизнь разработчика проще, но это приносит проблемы в плане архитектуры кода. 
во-первых, они несут методы, которые не во всех пакетах требуются
во-вторых, другие пакеты привязываются к пакету, где хранится супер-интерфейс
в-третьих, не получится минимальными усилиями применять структурные паттерны проектирования к типам, которые должны соответствовать этому супер-интерфейсу. 
например, если ты захочешь добавить кэширование в некоторые методы стораджа с помощью декоратора, то в нем придется создавать все методы, которые на самом деле может быть и не нужны в целевом пакете для использования декоратора.

в общем, код становится сложнее. лучше делать маленькие неэкспортируемые интерфейсы в тех пакетах, где тебе нужно с ними работать

2024-06-26 15:42 UTC, far4599 commented on internal/storage/db_test.go
> +	_, errCreate := os.Create("/test.json")
для создания временных файлов стоит использовать метод [os.CreateTemp()](https://pkg.go.dev/os#CreateTemp)

2024-06-27 03:06 UTC, mrkovshik commented on cmd/server/server.go
> +	if err := metricService.StoreMetrics(ctx); err != nil {
да, все верно. Вроде там в одном из инкрементов было такое требование, что должен делаться дамп при завершении работы.  Ты намекаешь на defer?

2024-06-27 08:39 UTC, far4599 commented on cmd/server/server.go
> +	if err := metricService.StoreMetrics(ctx); err != nil {
а по какой причине функция `apiService.RunServer(ctx)` может выйти? как ты проверяешь, что метод `metricService.StoreMetrics(ctx)` вообще вызывается?

2024-06-28 02:53 UTC, mrkovshik commented on cmd/agent/agent.go
исправил

2024-06-28 02:53 UTC, mrkovshik commented on bm_test.go
исправил

2024-06-28 03:48 UTC, mrkovshik commented on internal/service/agent/request.go
>  	req, err := http.NewRequest(http.MethodGet, "", nil)
не понял, это же не тестовый запрос, а настоящий

2024-06-28 03:49 UTC, mrkovshik commented on api/rest/api.go
> +	s.logger.Fatal(http.ListenAndServe(s.config.Address, r))
вроде отделил

2024-06-28 03:50 UTC, mrkovshik commented on api/rest/example_test.go
перенес

2024-06-28 03:54 UTC, mrkovshik commented on api/rest/example_test.go
> +func Example() {
тут не понял - если я изменю сигнатуру, то пример не скомпилируется

2024-06-28 03:54 UTC, mrkovshik commented on api/rest/handlers.go
>  func (s *Server) UpdateMetricFromJSON(ctx context.Context) func(res http.ResponseWriter, req *http.Request) {
переделал

2024-06-28 04:00 UTC, mrkovshik commented on api/rest/handlers.go
>  func (s *Server) UpdateMetricFromJSON(ctx context.Context) func(res http.ResponseWriter, req *http.Request) {
разделил контексты управления сервером и контексты в хендлерах - теперь работа хендлера управляется контекстом запроса, чтобы отменять выполнение при отмене запроса. Сервер же ждет сигнала из main

2024-06-28 04:00 UTC, mrkovshik commented on api/rest/handlers.go
>  func (s *Server) UpdateMetricsFromJSON(ctx context.Context) func(res http.ResponseWriter, req *http.Request) {
поправил

2024-06-28 04:13 UTC, mrkovshik commented on api/rest/middleware.go
>  		clientSig := r.Header.Get(`HashSHA256`)
исправил. проверять не нужно, потому что io.ReadAll инициализирует возвращаемый слайс через make, а это уже не nil

2024-06-28 04:14 UTC, mrkovshik commented on api/rest/handlers.go
>  		var ctx = context.Background()
исправил

2024-06-28 04:15 UTC, mrkovshik commented on api/rest/rest_api_test.go
уберу к следующему спринту, пока не успеваю

2024-06-28 04:18 UTC, mrkovshik commented on cmd/server/server.go
> +	if err := metricService.StoreMetrics(ctx); err != nil {
теперь RunServer выходит по отмене контекста. Про проверку выполнения не понял - залогировать что ли ее?

2024-06-28 04:25 UTC, mrkovshik commented on internal/service/storage.go
>  type Storage interface {
не совсем представляю как его разделять. В базе только одна таблица - с метриками. Сам интерфейс не такой уж и большой, 7 методов, по сути даже 5 можно сделать. Надо подумать

2024-06-28 04:37 UTC, far4599 commented on cmd/server/server.go
> +	if err := metricService.StoreMetrics(ctx); err != nil {
сам сервер с контекстом никак не связан. для его остановки существует отдельный метод, который нужно декларативно вызывать. но эту тему вы будуте проходить в следующем спринте. 
посмотри еще раз на задание, где сохранение вы добавляли. там написано, что бэкап нужно делать с интервалом раз в 300 секунд.

2024-06-28 04:38 UTC, far4599 commented on internal/service/agent/request.go
>  	req, err := http.NewRequest(http.MethodGet, "", nil)
точно. сорри. тут я не разобрался.

2024-06-28 04:48 UTC, far4599 approved these changes

2024-06-28 04:48 UTC, far4599 commented on api/rest/api.go
> +	case <-ctx.Done():
вот тут тебе нужно дергать метод остановки сервера. но для этого его нужно создать как объект, в горутине запустить, а тут дернуть метод объекта

2024-06-28 04:48 UTC, far4599 commented on api/rest/handlers.go
> +func (s *Server) UpdateMetricFromJSON() func(w http.ResponseWriter, r *http.Request) {
улучшение: а зачем тут делать замыкание? можешь сразу код вложенной функции, а не возвращать ее через return

2024-06-28 04:48 UTC, far4599 commented on api/rest/handlers.go
> +		ctx := r.Context()
молодец, что разобрался

2024-06-28 04:48 UTC, far4599 commented on api/rest/rest_api_test.go
ок

2024-06-28 04:48 UTC, far4599 commented on api/rest/api.go
> +	case <-ctx.Done():
а вообще лучше сделать наоборот. ошибку от Listen возращай сразу, а в грутине оставь select. тогда не придется использовать канал errCh
по большому счету, нет смысла даже завершать горутину, потому что остановка сервера - это фатальная для приложения ситуация, после которого оно выйдет и чистить память уже не придется. 
но для практики вот тебе 2 задания:
1. сделай так, чтобы горутина тоже завершалась, если основная функция вышла с ошибкой
2. сервер может возвращать особый формат ошибки, который не нужно логгировать - принудительная остановка. А если ошибки не этого типа, то их нужно логгировать или возращать из этой функции.

2024-06-28 04:58 UTC, mrkovshik commented on cmd/server/server.go
> +	if err := metricService.StoreMetrics(ctx); err != nil {
![image](https://github.com/mrkovshik/yametrics/assets/115558189/67be9c48-c5c7-4a97-bfb0-f1b5c9eb34b4)

2024-06-28 05:00 UTC, mrkovshik commented on api/rest/handlers.go
> +func (s *Server) UpdateMetricFromJSON() func(w http.ResponseWriter, r *http.Request) {
Точно)

2024-06-28 06:38 UTC, far4599 commented on api/rest/example_test.go
> +func Example() {
а зачем тебе пример компилировать? делаешь функцию TestExample(t *testing.T) и любой, кто на твой пример смотри, может его запустить

2024-08-07 02:44 UTC, merged